[package]
name = "denispionicul/partymodule"
version = "1.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@1.5.0"
Trove = "sleitnick/trove@1.0.1"
Option = "sleitnick/option@1.0.4"
Promise = "evaera/promise@4.0.0"